travis:
  secure:
    BINSTAR_TOKEN: ZL9Vcvh9iNa7KVXAuWwLWOykm35n2tiF84GGbDSsVPyXmsAuailfGG5e+nf7WZ/8WFiKSsKBvgDlYigKIAzVdXWpmXLL1g5kvUH88qv77OLrbKT33IR6dWe/6sVM/sACs83s9wDBjW6cNRgg+NM7Y/VoHD5Jsig6NNlxYS1JNUE6EfUFMzQcbXum3sbSLZskLtRhxRUhPzD/FYaQbmA6003FhjE+5APk98jqKtaGMEWzhvAidJanOHnWeDRwew39007WGlJiybT857ZcXXiM3tZHH/gh88UDmGboptN0XlWKUgQ+xUwNqSoHQAZ/rQTin1dOWhPRVOKXtZb+QtlXyfgjCWRNGxiVXZ4c+TrbS6XeIoSb1QP+nK5iUdkFY4i0Jw2p+QycsbflyiN3rJ2zvaEdhgfjEKVVXB6ORyIAWeEPAcOl4yP/mHj3o3WBicer7stObjjgHm0raZ5TUvOTi0A20RIrJKaqPIA4fPDsta3XZFYB7VqPyCwWmbc7gFfMH8a5UvvvXYjLy3kIYwO61Pn2eq0mjjUC8dZWDPMxq+1CJpi3732frqv71q8qCNZ6n4AEwtS1YXT6cRlsOlD/hta1hCB7rlMpOU3VV7UrpeXJYVOcUZwfVeSpaBg48q8ER+Q/wo4OmYqhfGD91OETKenM3vrRxE1olxeD07C8Xvk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
